version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: flipswitch
      POSTGRES_PASSWORD: flipswitch
      POSTGRES_DB: flipswitch
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  app:
    build: .
    command: sh -c "npm install && npx prisma migrate deploy || true && npx prisma db push && npm run prisma:seed || true && npm run dev"
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      GITHUB_ID: ${GITHUB_ID}
      GITHUB_SECRET: ${GITHUB_SECRET}
      GOOGLE_ID: ${GOOGLE_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      REALTIME_PORT: ${REALTIME_PORT}
      NEXT_PUBLIC_WS_URL: ${NEXT_PUBLIC_WS_URL}
    depends_on:
      - db
      - redis

volumes:
  db-data:
  redis-data:
